name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --release

    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: snikket-apns
        path: |
            target/release/snikket-apns
